### ISSUE TITLE
PBS Slave Computer

### ISSUE THREAD

**Issue by bingding** [biouno/pbs-plugin#8] opened 2015-07-21 15:11 UTC
I got the following error messages. Could you please give me hint how to setup PBS slave computer in Jenkins. thanks
00:00:00 Started by user anonymous
00:00:00 [EnvInject] - Loading node environment variables.
00:00:00 Building in workspace /home/bhuang/.jenkins/jobs/pbs-test/workspace
00:00:00 Submitting PBS job...
00:00:00 ERROR: You need  PBS Slave Computer in order to submit PBS jobs
00:00:00 Finished: FAILURE

**Comment by kinow** [comment] 2015-07-22 06:54
Hi @bingding, you need to create a new PBS slave in Jenkins first, and then use the right lavel in your job. We are working on a new release, and the number 1 priority will be to create documentation, either in biouno.org, or here using GitHub Wiki pages. 

Let me know if that works.

**Comment by bingding** [comment] 2015-07-22 07:40
I still can't find a way how to create a new PBS slave in Jenkins. I have installed torque PBS in the same sever hosting Jenkins, which manage several computing nodes. I would like  to have Jenkins to manage our pipeline developed in batch shell scripts using PBS. When will be the new release? thanks
Bingding

**Comment by kinow** [comment] 2015-07-22 08:23
I'll finish some work on Active Choices (another plug-in originated in biouno) and will start writing the documentation. I'll post the link for the draft documentation here so you can take a look and provide some feedback (in case you have time for that :) )

**Comment by kinow** [comment] 2015-07-22 10:38
Merged all the pull requests in Active Choices! Next in the list: PBS plug-in :)

**Comment by kinow** [comment] 2015-07-24 08:05
Being worked in issue #9. We'll update our documentation in the next days, and will announce a new release in our mailing list. So stay tuned. As the issue is being linked to the other one I believe GitHub will notify you too, but you may want to watch #9

**Closed as completed by kinow** 2015-07-24 08:05 UTC
Labels: documentation
